from tkinter import *
from tkinter.ttk import *
window=Tk()
window.title("CALCULATOR-PRO")
window.resizable(True,False)
photo=PhotoImage(file='cal.png')
window.iconphoto(False,photo)
num=StringVar()
ans=StringVar()
def equal():
     try:
      ans=str(eval(num.get()))
      num.set(str(ans))
     except (SyntaxError,NameError,TypeError):
      num.set('ERROR')   
def clear():
     num.set('')
def press(event):
   button = event.widget.cget("text")
   num.set(num.get()+str(button))
def back():
   num.set(num.get()[:len(num.get())-1])
   
box=Entry(window,width=52,textvariable=num)
box.grid(row=0,column=0,columnspan=10)
button1=Button(window,text='1')
button1.bind('<Button-1>',press)
button1.grid(row=1,column=0)
button2=Button(window,text='2')
button2.bind('<Button-1>',press)
button2.grid(row=5,column=0)
button3=Button(window,text='3')
button3.bind('<Button-1>',press)
button3.grid(row=3,column=0)
button4=Button(window,text='4')
button4.bind('<Button-1>',press)
button4.grid(row=1,column=1)
button5=Button(window,text='5')
button5.bind('<Button-1>',press)
button5.grid(row=5,column=1)
button6=Button(window,text='6')
button6.bind('<Button-1>',press)
button6.grid(row=3,column=1)
button7=Button(window,text='7')
button7.bind('<Button-1>',press)
button7.grid(row=1,column=2)
button8=Button(window,text='8')
button8.bind('<Button-1>',press)
button8.grid(row=5,column=2)
button9=Button(window,text='9')
button9.bind('<Button-1>',press)
button9.grid(row=3,column=2)
button0=Button(window,text='0')
button0.bind('<Button-1>',press)
button0.grid(row=1,column=3)
button_equal=Button(window,text='=',command=equal).grid()
clear=Button(window,text='c',command=clear).grid(row=5,column=3)
button_add=Button(window,text='+')
button_add.bind('<Button-1>',press)
button_add.grid(row=3,column=3)
button_mul=Button(window,text='*')
button_mul.bind('<Button-1>',press)
button_mul.grid(row=5,column=2)
button_sub=Button(window,text='-')
button_sub.bind('<Button-1>',press)
button_sub.grid(row=6,column=2)
button_div=Button(window,text='/')
button_div.bind('<Button-1>',press)
button_div.grid(row=6,column=1)
back=Button(window,text='<--',command=back).grid(row=6,column=3)
button_point=Button(window,text='.')
button_point.bind('<Button-1>',press)
button_point.grid(row=1,column=4)
window.mainloop()
